name: StackViewAnimation
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "10.0"
targets:
  StackViewAnimation:
    type: application
    platform: iOS
    sources: [StackViewAnimation]